#!/usr/bin/env node
/** Sync version from package.json → Cargo.toml, tauri.conf.json, UI assets, package-lock.json */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = pkg.version;
const productName = 'Musomo Tracker';

if (!version || typeof version !== 'string') {
  console.error('package.json missing version');
  process.exit(1);
}

function replaceOnce(content, pattern, replacement, label) {
  if (!pattern.test(content)) {
    console.error(`sync-version: pattern not found in ${label}`);
    process.exit(1);
  }
  return content.replace(pattern, replacement);
}

// Cargo.toml
const cargoPath = path.join(root, 'src-tauri', 'Cargo.toml');
let cargo = fs.readFileSync(cargoPath, 'utf8');
cargo = replaceOnce(cargo, /^version = "[^"]+"/m, `version = "${version}"`, 'Cargo.toml');
fs.writeFileSync(cargoPath, cargo);

// tauri.conf.json
const tauriConfPath = path.join(root, 'src-tauri', 'tauri.conf.json');
const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
tauriConf.version = version;
tauriConf.productName = productName;
fs.writeFileSync(tauriConfPath, `${JSON.stringify(tauriConf, null, 2)}\n`);

// src/version.js — loaded by UI
const versionJs = `/* Generated by scripts/sync-version.mjs — do not edit by hand */
window.MUSOMO_APP_NAME = ${JSON.stringify(productName)};
window.MUSOMO_APP_VERSION = ${JSON.stringify(version)};
`;
fs.writeFileSync(path.join(root, 'src', 'version.js'), versionJs);

// Cache-bust query strings in HTML + sidebar version badge fallback
for (const rel of ['src/tracker-studio/index.html', 'src/tracker-studio/mini.html']) {
  const htmlPath = path.join(root, rel);
  let html = fs.readFileSync(htmlPath, 'utf8');
  html = html.replace(/\?v=[0-9.]+/g, `?v=${version}`);
  if (rel.endsWith('index.html')) {
    html = html.replace(/id="appVersionBadge">v[0-9.]+</, `id="appVersionBadge">v${version}<`);
  }
  fs.writeFileSync(htmlPath, html);
}

// package-lock.json
const lockPath = path.join(root, 'package-lock.json');
if (fs.existsSync(lockPath)) {
  const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
  lock.version = version;
  if (lock.packages?.['']) lock.packages[''].version = version;
  fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

console.log(`Synced version ${version} (${productName})`);
